app/app/src/client/tsconfig.json

client측 tsconfig 수정
allowJs: true -> false
strict: false -> true

Update client tsconfig

---

app/frontend/layout/footer.tsx
app/frontend/layout/header.tsx
app/frontend/pages/_app.tsx
app/frontend/pages/help/index.tsx
app/frontend/pages/index.tsx
app/frontend/styles/Footer.module.css
app/frontend/styles/Header.module.css
app/frontend/styles/Home.module.css

Add header

---

.gitignore
app/crawler/Dockerfile
app/crawler/Makefile
app/crawler/README.md
app/crawler/includes/IrcClient.hpp
app/crawler/includes/IrcError.hpp
app/crawler/includes/IrcSocket.hpp
app/crawler/includes/utils.hpp
app/crawler/srcs/IrcClient.cpp
app/crawler/srcs/IrcError.cpp
app/crawler/srcs/IrcSocket.cpp
app/crawler/srcs/main.cpp
app/crawler/srcs/utils.cpp
app/db/Dockerfile
app/db/Readme.md
app/db/srcs/mariadb-server.cnf
docker-compose.yaml

Add chat crawler

---

app/frontend/pages/_app.tsx
app/frontend/pages/help/index.tsx

Refactor layout

---

app/frontend/package-lock.json
app/frontend/package.json

chartjs2 라이브러리 추가
https://github.com/reactchartjs/react-chartjs-2

Add chartjs2

---

app/backend/package-lock.json
app/backend/package.json
app/backend/src/app.module.ts
app/backend/src/schema.gql
app/backend/src/statistics/statistics.entity.ts
app/backend/src/statistics/statistics.module.ts
app/backend/src/statistics/statistics.resolver.spec.ts
app/backend/src/statistics/statistics.resolver.ts
app/backend/src/statistics/statistics.service.spec.ts
app/backend/src/statistics/statistics.service.ts
app/frontend/next-env.d.ts

Add graphQL

---

app/frontend/layout/header.tsx
app/frontend/pages/index.tsx
app/frontend/styles/Header.module.css
app/frontend/styles/Home.module.css

메인페이지와 header layout의 검색 바에 검색 버튼을 추가함

Add Search Button

---

app/backend/Dockerfile
app/backend/entrypoint.sh
app/crawler/srcs/IrcClient.cpp
app/frontend/Dockerfile
app/frontend/entrypoint.sh
docker-compose.yaml

- Dockefile 추가
- node_modules가 설치된 이미지 사용
- 개발시 remote-container 사용 필요

Hna refactor backend

---

app/backend/src/chatfire/chatfire.resolver.ts
app/backend/src/chatfire/chatfire.service.ts
app/backend/src/schema.gql

- day top 쿼리를 id검색에서 nick 검색으로 변경

Fix getDayTop from id to nick

---

app/frontend/components/hooks/useWindowSize.tsx
app/frontend/components/pages/help/faq.tsx
app/frontend/layout/footer.tsx
app/frontend/pages/[streamer_nick].tsx
app/frontend/pages/help/index.tsx
app/frontend/pages/index.tsx
app/frontend/styles/Header.module.css
app/frontend/styles/Help.module.css
app/frontend/styles/Home.module.css
app/frontend/styles/Statistics.module.css

apply media

---

app/frontend/layout/header.tsx
app/frontend/pages/[streamer_nick].tsx

Fix #33 graph bug

---

app/backend/src/chatfire/chatfire.resolver.ts
app/backend/src/chatfire/chatfire.service.ts
app/backend/src/entities/chatfire.entity.ts
app/backend/src/schema.gql

Add Current Chatfire query

---

app/frontend/components/pages/help/contactus.tsx
app/frontend/layout/header.tsx
app/frontend/pages/index.tsx

Production 환경에서도 data fetch가 가능토록 변경

Fix data fetch in client side

---

app/crawler/srcs/IrcClient.cpp

join 메세지가 10초 20개 제한이라서 
약 20개가 되기 이전에 10초 sleep하도록 수정

Add sleep to irc join message

---

app/frontend/components/pages/help/contactus.tsx

Refactor frontend

---

app/frontend/Dockerfile
app/frontend/components/hooks/useAutoComplete.tsx
app/frontend/components/pages/help/contactus.tsx
app/frontend/components/pages/help/faq.tsx
app/frontend/layout/footer.tsx
app/frontend/layout/header.tsx
app/frontend/pages/[streamer_nick].tsx
app/frontend/pages/index.tsx

mui v4를 사용하던 import 문 수정 및
data fetch query 문 수정

Fix mui import && data fetch

---

app/analyzer/srcs/main.py
app/backend/src/chatfire/chatfire.service.ts
app/backend/src/entities/chatfire.entity.ts
app/backend/src/entities/legend.entity.ts
app/backend/src/entities/streamer.entity.ts
app/backend/src/entities/topword.entity.ts
app/backend/src/schema.gql
app/backend/src/streamer/dto/create-one.args.ts
app/backend/src/streamer/streamer.resolver.ts
app/backend/src/streamer/streamer.service.ts
app/backend/src/topword/topword.service.ts
app/crawler/srcs/IrcClient.cpp
app/db/srcs/create_table.sql
app/frontend/interfaces/chat-fire.ts
app/frontend/interfaces/streamer.ts
app/frontend/pages/[streamer_nick].tsx

Update streamer_id to streamer_login

---

app/frontend/components/hooks/useBrushChart.tsx
app/frontend/components/hooks/useChart.tsx
app/frontend/components/hooks/useLineChart.tsx
app/frontend/package-lock.json
app/frontend/package.json
app/frontend/pages/[streamer_nick].tsx

Use apex charts

---

app/crawler/Dockerfile
app/crawler/includes/ChatStorage.hpp
app/crawler/includes/IrcClient.hpp
app/crawler/srcs/ChatStorage.cpp
app/crawler/srcs/IrcClient.cpp

1. 크롤러 첫 실행시 streamer list 삽입하는 부분 한 줄의 쿼리로 실행하도록 변경
2. 챗 하나당 INSERT 문을 실행하던걸 50개씩 모아서 INSERT 문을 호출하도록 변경
55be8225788b44c4998e7e74db9fc4c8b04550c3 <-- 이 커밋이 핵심이니까 여기만 보셔도 무방해요

Refactor crawler

---

app/backend/src/chatfire/chatfire.service.ts

1. DayTop 값이 Entire 값과 같은 문제 -> 날짜가 sql date 형식으로 변환되지 않아서 생긴 문제
2. legend 테이블에 값이 저장되지 않는 문제 -> await을 안해줘서 생긴 문제
fix #90

Hna fix backend chatfire top

---

app/analyzer/srcs/main.py

Add chatlog delete

---

app/analyzer/srcs/main.py

Puntuation -> Punctuation 오타 수정

Fix typo Puntuation -> Punctuation

---

app/backend/controllers/chatfire_c.go
app/backend/controllers/streamer_c.go
app/backend/controllers/topword_c.go
app/backend/daemons/chatlog_d.go
app/backend/daemons/legend_d.go
app/backend/daemons/streamer_d.go
app/backend/db/maria_db.go
app/backend/db/redis_db.go
app/backend/go.mod
app/backend/go.sum
app/backend/main.go
app/backend/routers/chatfire_r.go
app/backend/routers/streamer_r.go
app/backend/routers/topword_r.go
app/backend/services/chatfire_s.go
app/backend/services/streamer_s.go
app/backend/services/topword_s.go
app/backend/utils/parse_time.go

* db 연결을 클래스에서 하도록 리팩토링
* 연산량이 많은 GetChatFireByInterval API에 redis 캐싱을 적용해서
interval 5 기준으로 response 시간을 5ms 에서 1ms 로 단축시킴

pref: use redis cache

---

app/analyzer/Dockerfile
app/analyzer/srcs/main.py
app/backend/daemons/streamer_d.go
app/backend/main.go
app/backend/models/chatfire_m.go
app/backend/services/chatfire_s.go
app/db/srcs/create_table.sql
app/frontend/components/StatisticsChart.tsx
app/frontend/pages/[streamerid].tsx

feat: add viewers in series

---

.gitignore
app/redis/redis.conf
docker-compose.yaml

feat: enable redis backup

---

app/analyzer/srcs/main.py
app/backend/docs/top-word/streamerId/get.md
app/backend/models/topword_m.go
app/backend/services/topword_s.go
app/db/srcs/create_table.sql
app/frontend/components/MostUsedTable.tsx
app/frontend/pages/[streamerid].tsx

feat: add top word count

---

app/backend/services/topword_s.go

fix: load old topword value bug fix

---

app/analyzer/srcs/main.py

top word count의 마지막(10번째) 사용횟수가 첫번째 사용횟수와 같은 버그 수정

fix: top word count bug

---

app/frontend/components/hooks/useAutoComplete.tsx
app/frontend/pages/not-found.tsx

feat: add not found page for handling 404

---

app/backend/controllers/statistics_c.go

statistics api의 캐시 생존 시간을 한시간에서 하루로 늘림

feat: update statistics cache expire time to day
